# Numpy Basics

In [234]:
import numpy as np

In [235]:
np.__name__

'numpy'

In [236]:
np.__version__

'1.19.2'

In [237]:
np.__doc__

'\nNumPy\n=====\n\nProvides\n  1. An array object of arbitrary homogeneous items\n  2. Fast mathematical operations over arrays\n  3. Linear Algebra, Fourier Transforms, Random Number Generation\n\nHow to use the documentation\n----------------------------\nDocumentation is available in two forms: docstrings provided\nwith the code, and a loose standing reference guide, available from\n`the NumPy homepage <https://www.scipy.org>`_.\n\nWe recommend exploring the docstrings using\n`IPython <https://ipython.org>`_, an advanced Python shell with\nTAB-completion and introspection capabilities.  See below for further\ninstructions.\n\nThe docstring examples assume that `numpy` has been imported as `np`::\n\n  >>> import numpy as np\n\nCode snippets are indicated by three greater-than signs::\n\n  >>> x = 42\n  >>> x = x + 1\n\nUse the built-in ``help`` function to view a function\'s docstring::\n\n  >>> help(np.sort)\n  ... # doctest: +SKIP\n\nFor some objects, ``np.info(obj)`` may provide a

A single integer in Python 3.4 actually contains four pieces:
* ob_refcnt,  a  reference  count  that  helps  Python  silently  handle  memory  alloca‐tion and deallocation
* ob_type, which encodes the type of the variable
* ob_size, which specifies the size of the following data members
* ob_digit, which contains the actual integer value that we expect the Python vari‐able to represent

PyObject_HEAD is the part of the structure containing the reference count, type code, and other pieces mentioned before.

a C integer is essentially a label for a position in memory whose bytes encode an integer value. A Python integer is a pointer to a position in memory containing all the Python object information, including the bytes that con‐ tain the integer value. This extra information in the Python integer structure is what allows Python to be coded so freely and dynamically. All this additional information in Python types comes at a cost, however, which becomes especially apparent in structures that combine many of these objects.

At the implementation level, the array essentially contains a single pointer to one con‐ tiguous block of data. The Python list, on the other hand, contains a pointer to a block of pointers, each of which in turn points to a full Python object like the Python integer we saw earlier. Again, the advantage of the list is flexibility: because each list element is a full structure containing both data and type information, the list can be filled with data of any desired type. Fixed-type NumPy-style arrays lack this flexibil‐ ity, but are much more efficient for storing and manipulating data.

### list and arrays

In [238]:
a = [3,4,5] #list

In [239]:
id(a)

140619520907072

In [240]:
b = ['4',7.4,8] #list can be of mulitiple elments
# as element is a separted python object and list contaings multiple pointers of different types of data types

In [241]:
id(b) 

140619520974400

In [242]:
c = np.array([a,b])

In [243]:
c # a numpy array only contains only one type of data type type pointer
# therefore it is faster than the list manipulation and bit less flexibile
# when an array of mulitple list of different kinds of data types numpy converts to highest data type (here strings)

array([['3', '4', '5'],
       ['4', '7.4', '8']], dtype='<U21')

In [244]:
a[0] = 9 # 1st element is altered

In [245]:
a

[9, 4, 5]

In [246]:
c #numpy array does not change

array([['3', '4', '5'],
       ['4', '7.4', '8']], dtype='<U21')

In [247]:
c[0] = 5

In [248]:
a

[9, 4, 5]

In [249]:
c = np.array([a,[3.3,5,6]])

In [250]:
c

array([[9. , 4. , 5. ],
       [3.3, 5. , 6. ]])

In [251]:
d = np.array(a)

In [252]:
d.shape

(3,)

In [253]:
a[0] = 0

In [254]:
d

array([9, 4, 5])

### creating array using python lists

numpy is buit over built-in package `array`

the ndarray object of the NumPy package. While Python’s array object provides efficient storage of array-based data, NumPy adds to this efficient operations on that data. We will explore these operations in later sec‐ tions; here we’ll demonstrate several ways of creating a NumPy array.

In [255]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [256]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [257]:
 np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [258]:
 np.array([1, 2, 3, 4], dtype=str)

array(['1', '2', '3', '4'], dtype='<U1')

In [259]:
 np.array([1, 2, 3, 4], dtype='str')

array(['1', '2', '3', '4'], dtype='<U1')

In [260]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Creating Arrays from Scratch

In [261]:
# Create a length-10 integer array filled with zeros
np.zeros([10,10], dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [262]:
 # Create a 3x5 floating-point array filled with 
np.ones([3, 5], dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [263]:
# Create a 3x5 array filled with 3.14 
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [264]:
np.full((3, 5), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [265]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [266]:
np.arange(0, 20, 2).reshape(2,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [267]:
# Create an array of five values evenly spaced between 0 and 1 
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [268]:
np.random.random((3, 3))

array([[0.65279032, 0.63505887, 0.99529957],
       [0.58185033, 0.41436859, 0.4746975 ],
       [0.6235101 , 0.33800761, 0.67475232]])

In [269]:
# Create a 3x3 array of normally distributed 
#random values 
# with mean 0 and standard deviation 1 
np.random.normal(0, 1, (3, 3))

array([[ 1.0657892 , -0.69993739,  0.14407911],
       [ 0.3985421 ,  0.02686925,  1.05583713],
       [-0.07318342, -0.66572066, -0.04411241]])

In [270]:
# Create a 3x3 array of random integers 
in the interval [0, 10) 
np.random.randint(0, 10, (3, 3))

array([[7, 2, 9],
       [2, 3, 3],
       [2, 3, 4]])

In [271]:
np.random.seed()

In [272]:
# Create a 3x3 identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [273]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that # memory location
np.empty(3)

array([1., 1., 1.])

In [274]:
np.empty((3,3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [275]:
np.empty([3,3])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

NumPy arrays contain values of a single type, so it is important to have detailed knowledge of those types and their limitations. Because NumPy is built in C, the types will be familiar to users of C, Fortran, and other related languages.

<insert figure>

$insert figure$

1. __Attributes of arrays__
_Determining the size, shape, memory consumption, and data types of arrays_

2. __Indexing of arrays__
_Getting and setting the value of individual array elements_

3. __Slicing of arrays__
_Getting and setting smaller subarrays within a larger array_

4. __Reshaping of arrays__
_Changing the shape of a given array
Joining and splitting of arrays
Combining multiple arrays into one, and splitting one array into many_


### 1. __Attributes of arrays__

In [276]:
np.random.seed() 

In [277]:
np.random.seed(0) # seed for reproducibility

In [278]:
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [279]:
print("x3 ndim: ", x3.ndim) 
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [280]:
print("x3 ndim: ", x1.ndim) 
print("x3 shape:", x1.shape)
print("x3 size: ", x1.size)

x3 ndim:  1
x3 shape: (6,)
x3 size:  6


In [281]:
x1

array([5, 0, 3, 3, 7, 9])

In [282]:
 print("dtype:", x3.dtype)

dtype: int64


Other attributes include itemsize,
which lists the size (in bytes) of each array 
element, and nbytes, which lists the total size
(in bytes) of the array:

In [283]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In general, we expect that nbytes is equal to itemsize times size.

### 2. __Indexing of arrays__

In [284]:
x1

array([5, 0, 3, 3, 7, 9])

In [285]:
x1[0]

5

In [286]:
x1[-1]

9

In [287]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [288]:
x2[0, 0]

3

In [289]:
x2[0]

array([3, 5, 2, 4])

In [290]:
x2[0][0]

3

In [291]:
x2[2, -1]

7

In [292]:
x2[2] [-1]

7

In [293]:
#can also modify values using any of the above index notation:

In [294]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [295]:
x1[0] = 3.14159 # this will be truncated! x1

In [296]:
x1

array([3, 0, 3, 3, 7, 9])

### 3. __Slicing of arrays__

__syntax:__
    
$$<x>[start:stop:step]$$

If any of these are unspecified, they default to the values start=0, stop=size of dimension, step=1


$<x>: $ numpy array name 



In [297]:
x = np.arange(10) 

In [298]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [299]:
x[:5] # first five elements

array([0, 1, 2, 3, 4])

In [300]:
 x[5:] # elements after index 5

array([5, 6, 7, 8, 9])

In [301]:
 x[4:7] # middle subarray

array([4, 5, 6])

In [302]:
x[::2] # every other element

array([0, 2, 4, 6, 8])

In [303]:
x[1::2] # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [304]:
x[::-1] # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [305]:
x[5::-2] # reversed every other from index 5

array([5, 3, 1])

#### Multidimensional subarrays

In [306]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [307]:
x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [308]:
x2[:3, ::2] # all rows, every other column


array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [309]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

### Accessing array rows and columns

One commonly needed routine is accessing single rows or columns of an array. You can do this by combining indexing and slicing, using an empty slice marked by a single colon (:)

In [310]:
print(x2[0, :]) # first row of x2


[12  5  2  4]


In [311]:
print(x2[:, 0]) # first column of x2

[12  7  1]


In the case of row access, the empty slice can be omitted for a more compact syntax:

In [312]:
print(x2[0]) # equivalent to x2[0, :]

[12  5  2  4]


#### Subarrays as no-copy views

array slices is that they return views rather than copies of the array data. This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies. Consider our two-dimensional array from before:

In [313]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [314]:
x2_sub = x2[:2, :2] 
print(x2_sub)

[[12  5]
 [ 7  6]]


In [315]:
x2_sub[0, 0] = 99 
print(x2_sub)

[[99  5]
 [ 7  6]]


In [316]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

#### __Creating copies of arrays__

In [317]:
x2_sub_copy = x2[:2, :2].copy() 
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [318]:
x2_sub_copy[0, 0] = 42 
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [319]:
print(x2)


[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### 3. __Reshaping of arrays__

In [320]:
grid = np.arange(1, 10).reshape((3, 3)) 
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


for this to work, the size of the initial array must match the size of the reshaped array. Where possible, the reshape method will use a no-copy view of the initial array, but with noncontiguous memory buffers this is not always the case.


common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix. You can do this with the reshape method, or more easily by making use of the newaxis keyword within a slice operation:

In [321]:
x = np.array([1, 2, 3])

In [322]:
x.ndim

1

In [323]:
x.shape

(3,)

In [324]:
x.size

3

In [325]:
# row vector via reshape
y = x.reshape((1, 3))
y

array([[1, 2, 3]])

In [326]:
y.shape

(1, 3)

In [327]:
# row vector via newaxis 
x[np.newaxis, :].ndim

2

In [328]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [329]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [330]:
x

array([1, 2, 3])

#### Array Concatenation

In [331]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [332]:
np.concatenate([[x], [y]])

array([[1, 2, 3],
       [3, 2, 1]])

In [333]:
np.concatenate([[x, y]])

array([[1, 2, 3],
       [3, 2, 1]])

In [334]:
np.concatenate([[x.T], [y.T]])

array([[1, 2, 3],
       [3, 2, 1]])

In [335]:
z = [99, 99, 99] 
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [336]:
grid = np.array([[1, 2, 3], [4, 5, 6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [337]:
# concatenate along the first axis 
np.concatenate([grid, grid])


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [338]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

For working with arrays of mixed dimensions, it can be clearer to use the np.vstack (vertical stack) and np.hstack (horizontal stack) functions:

In [339]:
x = np.array([1, 2, 3]) 
grid = np.array([[9, 8, 7],[6, 5, 4]])

In [340]:
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [341]:
 # horizontally stack the arrays 
y = np.array([[99],[99]]) 
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

Similarly, np.dstack will stack arrays along the third axis

 some shape dimens should be same for concatenation

#### Spliting of arrays

`np.split`, `np.hsplit`, and `np.vsplit` 

In [342]:
x=[1,2,3,99,99,3,2,1] 
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


Notice that N split points lead to N + 1 subarrays. The related functions np.hsplit and np.vsplit are similar:

In [343]:
grid = np.arange(16).reshape((4, 4)) 
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [344]:
upper, mid,lower = np.vsplit(grid, [1,3])
print(upper)
print(mid)
print(lower)

[[0 1 2 3]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]]


In [345]:
left, right = np.hsplit(grid, [2]) 
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


Similarly, `np.dsplit` will split arrays along the third axis.