# Comparisons, Masks, and Boolean Logic

Boolean masks to examine and manipulate values within NumPy arrays. Masking comes up when you want to extract, modify, count, or otherwise manipulate values in an array based on some criterion: for example, you might wish to count all values greater than a certain value, or perhaps remove all out‐ liers that are above some threshold. In NumPy, Boolean masking is often the most efficient way to accomplish these types of tasks.

In [2]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])

In [4]:
x < 3

array([ True,  True, False, False, False])

In [5]:
x > 3

array([False, False, False,  True,  True])

In [6]:
x >= 3

array([False, False,  True,  True,  True])

In [7]:
x != 3

array([ True,  True, False,  True,  True])

In [8]:
(2*x)==(x**2)

array([False,  True, False, False, False])

In [10]:
np.less(x, 3) #equivalent numpy ufunc

array([ True,  True, False, False, False])

In [11]:
rng = np.random.RandomState(0) 
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [14]:
np.less_equal(x,6)

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False,  True]])

In [16]:
np.count_nonzero(x <= 6)

9

In [17]:
np.sum(x <= 6)

9

In [18]:
(x <= 6).sum()

9

In [21]:
# how many values less than 6 in each row? 
np.sum(x < 6, axis=1)

array([4, 2, 2])

quickly checking whether any or all the values are true, we can use (you guessed it) `np.any()` or `np.all()`:

In [22]:
np.any(x > 8)

True

In [23]:
np.all(x > 8)

False

In [24]:
np.all(x < 10)

True

In [25]:
# are all values in each row less than 8? 
np.all(x < 8, axis=1)

array([ True, False,  True])

Python has built-in sum(), any(), and all() functions. These have a different syntax than the NumPy versions, and in particular will fail or produce unintended results when used on multidimensional arrays. Be sure that you are using np.sum(), np.any(), and np.all() for these examples!

In [ ]:
np.sum((inches > 0.5) & (inches < 1))
np.sum(~( (inches <= 0.5) | (inches >= 1) ))

### Boolean Arrays as Masks

In [27]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [28]:
x < 5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [29]:
x[x < 5]

array([0, 3, 3, 3, 2, 4])

##### Using the Keywords and/or Versus the Operators &/|

## Fancy indexing

Fancy indexing is like the simple indexing we’ve already seen, but we pass arrays of indices in place of single scalars.