# Lists

* Most similar looking *container* data structure to an array in Python is built-in `list`.
* 'list' is a collection of items, & these items can be anything.
* But they are not efficient enough to handle Matrix/Linear algebra due to lack of basic functions required in these operations and suffer through storage and coumputation effeciency if `list` are used for such purposes.

## How does 'list' looks in python?

In [118]:
a = ['2',3,4,'ufl.edu']
x = [3,55,66,33]
y = [3.7,0.45,33,0]
f = ['this','is','about','?']

In [119]:
print(a)

['2', 3, 4, 'ufl.edu']


### Assignment in python does not necessarily mean assignment of value but rather assignment of pointer
**irrespective of what you use (numpy, list, or any non container variables)**

In [120]:
b = a # b points to a
c = a.copy() # c points to different memory location that of a but contains copied values of a

In [121]:
a[0] = 'apple'
print(b)

['apple', 3, 4, 'ufl.edu']


In [122]:
print(id(a))

140289343647424


In [123]:
print(id(b))

140289343647424


In [124]:
id(b)==id(a)

True

In [125]:
c

['2', 3, 4, 'ufl.edu']

# Numpy

In [126]:
import numpy as np

* `as` is used to give short nicknames for ease of coding.
* These nicknames can be anything.
* but **conventions are followed** .

In [178]:
arr_a = np.array([2,3]) 

In [128]:
arr_b = arr_a

In [129]:
arr_a[0] = 100

In [130]:
arr_b

array([100,   3])

In [131]:
arr_b  = arr_a.copy()

In [132]:
arr_a[0] = 200

In [133]:
arr_b

array([100,   3])

### Numpy array differ from Lists
1. Numpy array is not collection of pointers to memory but have actual values
2. All the elements in a *numpy* array should be of same 'type'
2. Numpy is designed to handle Linear Algebra with predefiend features

In [134]:
print('x:',x)
print('y:',y)
print('a:',a)

x: [3, 55, 66, 33]
y: [3.7, 0.45, 33, 0]
a: ['apple', 3, 4, 'ufl.edu']


In [135]:
arr_b = np.array([a,x])
arr_b

array([['apple', '3', '4', 'ufl.edu'],
       ['3', '55', '66', '33']], dtype='<U7')

In [136]:
arr_b.dtype

dtype('<U7')

In [137]:
arr_b = np.array([x,y])

In [138]:
arr_b

array([[ 3.  , 55.  , 66.  , 33.  ],
       [ 3.7 ,  0.45, 33.  ,  0.  ]])

In [139]:
arr_b.dtype

dtype('float64')

In [140]:
arr_b = np.array([x,y],dtype=int)

In [141]:
arr_b

array([[ 3, 55, 66, 33],
       [ 3,  0, 33,  0]])

# **Question** 
## What will the `dtype` if following is used: np.array([x,a,y])?

____________

## Above we say that how one can use `list` to declare numpy arrays but there are other functions built-in numpy package to do so too.

**Create a length-10 integer array filled with zeros**

In [100]:
np.zeros([10,10])#dtype=int)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

**Create a 3x5 floating-point array filled with**


In [103]:
np.ones([3, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**Create a 3x5 array filled with 3.14**

In [105]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [142]:
np.full((3, 5), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265]])

**Create an array filled with a linear sequence
Starting at 0, ending at 20, stepping by 2**

In [144]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [179]:
x = np.arange(6)

In [180]:
x

array([0, 1, 2, 3, 4, 5])

*NOTICE in `np.arange` the upper limit **is not** inclusive*

**Create an array of five values evenly spaced between 0 and 1**


In [145]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

*NOTICE in `np.linspace` the upper limit **is** inclusive*

**Create an uninitialized 3 x 3 matrix of three integers**

In [146]:
np.empty([3,3])

array([[ 8.02815969e-31, -1.60563194e-30,  4.01407985e-31],
       [-1.60563194e-30,  3.49224947e-30, -1.08380156e-30],
       [ 4.01407985e-31, -1.08380156e-30,  6.22182376e-31]])

**Create a 3x3 identity matrix**

In [148]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Create a 3x3 array of normally distributed 
random values with mean 0 and standard deviation 1**

In [151]:
np.random.normal(0, 1, (3, 3))

array([[ 0.2489563 ,  0.32832387,  1.56832064],
       [ 1.63690262,  0.08551579, -1.97339529],
       [-0.11909261, -0.74013813, -0.19940772]])

**Create a 3x3 array of random integers in the interval [0, 10)** 

In [152]:
np.random.randint(0, 10, (3, 3))

array([[9, 7, 4],
       [7, 8, 0],
       [8, 9, 5]])

# Attributes of Array

* __.dtype__
* __.shape__
* __.ndim__
* __.size__
_____
* __.data__
* __.itemsize__
* __.nbytes__

In [157]:
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [158]:
print("x3 ndim: ", x3.ndim) 
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [159]:
print("x3 ndim: ", x1.ndim) 
print("x3 shape:", x1.shape)
print("x3 size: ", x1.size)

x3 ndim:  1
x3 shape: (6,)
x3 size:  6


# **Question** 
## What will .ndim, .shape, .size for `x2`? 

_______________

# Indexing Of Arrays

In [160]:
x1

array([2, 8, 8, 7, 3, 5])

In [161]:
x1[0]

2

In [162]:
x1[-1]

5

In [169]:
x2

array([[5, 2, 2, 3],
       [4, 5, 9, 9],
       [3, 4, 1, 8]])

In [170]:
x2[0]

array([5, 2, 2, 3])

In [175]:
x2[0,0]#recommended

5

In [173]:
x2[0][0]

5

In [176]:
x1[0] = 3.14159 

In [177]:
x1

array([3, 8, 8, 7, 3, 5])

In [168]:
x1[-6:-3]

array([2, 8, 8])

*NOTICE here the upper limit **is not** inclusive*

In [196]:
x = np.array([i**2 for i in range(5)])

In [197]:
x.shape

(5,)

In [198]:
x.T

array([ 0,  1,  4,  9, 16])

In [199]:
x.T.shape

(5,)

In [200]:
x.ndim

1

In [201]:
x.T@x

354

In [202]:
x@x

354

In [203]:
x = x.reshape(5,1)

In [204]:
x

array([[ 0],
       [ 1],
       [ 4],
       [ 9],
       [16]])

In [205]:
x.T@x

array([[354]])

In [206]:
x@x.T

array([[  0,   0,   0,   0,   0],
       [  0,   1,   4,   9,  16],
       [  0,   4,  16,  36,  64],
       [  0,   9,  36,  81, 144],
       [  0,  16,  64, 144, 256]])

In [207]:
x.ndim

2

In [1]:
import numpy as np

In [5]:
A = np.array([[i for i in range(5)],[i for i in range(5,10)]])

In [6]:
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
A[1]

array([5, 6, 7, 8, 9])

In [13]:
A[1][:]

array([5, 6, 7, 8, 9])

In [14]:
A[:][2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [17]:
A[:][1]

array([5, 6, 7, 8, 9])

In [22]:
A[1,2]

7

In [23]:
A[1][2]

7

In [24]:
A[:][2]

IndexError: index 2 is out of bounds for axis 0 with size 2